server:
  port: 8090
  context-path: /

mybatis:
  mapper-locations: classpath*:com/liaoyin/lyproject/mapper/*.xml
  executor-type: simple
  type-aliases-package : com.liaoyin.lyproject.entity
  configuration:
    call-setters-on-nulls: true

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://47.75.135.84:3306/cs_365?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true&autoReconnect=true&useSSL=false&useAffectedRows=true&autoReconnect=true
    username: root
    password: Ly666
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 2
    maxWait: 60000
    minIdle: 1
  http:
    encoding:
      charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

project:
  properties:
    files: message.properties

